name: gromart_customer
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.2.6+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bluetooth_thermal_printer: ^0.0.6
  bottom_picker: ^2.3.3
  cached_network_image: ^3.3.1
  clipboard: ^0.1.3
  cloud_firestore: ^4.14.0
  cupertino_icons: ^1.0.6
  dotted_border: ^2.1.0
  easy_localization: ^3.0.3
  esc_pos_utils: ^1.1.0
  firebase_auth: ^4.16.0
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^15.0.4
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.11
  flutter_facebook_keyhash: ^0.0.4
  flutter_local_notifications: ^16.3.0
  flutter_native_image: ^0.0.6+1
  flutter_paypal_native: ^2.1.0
  flutter_polyline_points: ^2.0.0
  flutter_qr_bar_scanner: ^3.0.2
  flutter_rating_bar: ^4.0.1
  flutter_share: ^2.0.0
  flutter_sound: ^9.2.13
  flutter_staggered_grid_view: ^0.7.0
  flutter_stripe: ^10.0.0
  flutter_widget_from_html: ^0.14.10+1
  flutterflow_paginate_firestore: ^1.0.3+1
  flutterwave_standard: ^1.0.7
  font_awesome_flutter: ^10.6.0
  geocoding: ^2.1.1
  geoflutterfire2: ^2.3.15
  geolocator: ^10.1.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.1
  image_picker: ^1.0.5
  intl: 0.19.0
  intl_phone_number_input: ^0.7.4
  location: ^5.0.3
  lottie: ^2.7.0
  mailer: ^6.0.1
  map_launcher: ^3.1.0
  mercadopago_sdk: ^1.3.0
  mime: ^1.0.4
  moor_flutter: null
  path: ^1.8.3
  path_provider: ^2.1.1
  paytm_allinonesdk: ^1.2.2
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  pinput: ^5.0.0
  progress_dialog_null_safe: ^1.0.7
  razorpay_flutter: ^1.3.5
  rect_getter: ^1.1.0
  scroll_to_index: ^3.0.1
  share: ^2.0.4
  shared_preferences: ^2.2.2
  smart_auth: ^2.0.0
  smooth_page_indicator: ^1.1.0
  story_view: ^0.16.0
  the_apple_sign_in: null
  url_launcher: ^6.2.1
  video_compress: ^3.1.2
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3

dependency_overrides:
  firebase_core: ^3.3.0
  webview_flutter: ^4.4.3
  google_maps_place_picker_mb: ^3.1.0
  uuid: ^4.0.0
  http: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/fonts/
    - assets/flags/
    - assets/json file/
    - assets/

  fonts:
    - family: Poppinsb
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppinsl
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: Poppinsm
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Poppinsr
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Poppinssb
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
