// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCXsqHDZQ1R9bZoqrphiyTUeFFa3xHHI8',
    appId: '1:721684596657:web:172e5403e30844361f9f90',
    messagingSenderId: '721684596657',
    projectId: 'ncrsabjiwala-e782c',
    authDomain: 'ncrsabjiwala-e782c.firebaseapp.com',
    storageBucket: 'ncrsabjiwala-e782c.appspot.com',
    measurementId: 'G-T5NYR9V7P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCXsqHDZQ1R9bZoqrphiyTUeFFa3xHHI8',
    appId: '1:721684596657:web:172e5403e30844361f9f90',
    messagingSenderId: '721684596657',
    projectId: 'ncrsabjiwala-e782c',
    storageBucket: 'ncrsabjiwala-e782c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi9bPJrbosHkVxwFBecr2sPMQyWtF3uRw',
    appId: '1:721684596657:ios:3937794dcb207e9c1f9f90',
    messagingSenderId: '721684596657',
    projectId: 'ncrsabjiwala-e782c',
    storageBucket: 'ncrsabjiwala-e782c.appspot.com',
    androidClientId: 'Place your key',
    iosClientId: 'Place your key',
    iosBundleId: 'com.ncrsabjiwala.customer',
  );
}
